import type { Language } from "@/lib/i18n";

const de = {
  metaTitle: "Dein persönliches KI-System | Patrick Cipic Grübener",
  metaDescription: "Arbeite mit KI an deinen eigenen Dateien statt in verstreuten Chats. Vorbereitetes KI-System für Selbstständige und Macher: einmalig 199 €.",
  eyebrow: "Dein persönliches KI-System",
  heroTitle: "Deine Arbeit gehört nicht in einen Chatverlauf.",
  heroText: "Du schreibst ein Angebot mit KI. Zwei Monate später willst du es ändern. Statt den richtigen Chat zu suchen, öffnest du die Datei in deinem System und arbeitest mit deinem KI-Agenten direkt daran weiter.",
  heroPoint: "Ein Ort für deine Dateien, deinen Kontext und deine Arbeitsregeln.",
  priceLabel: "Einmaliger Paketpreis",
  buy: "Jetzt für 199 € kaufen",
  enquire: "Kauf anfragen",
  talk: "Gespräch buchen",
  checkoutPending: "Der direkte Checkout wird vorbereitet. Du kannst den Kauf jetzt anfragen.",
  teaserTitle: "KI für deine eigene Arbeit: ein System statt verstreuter Chats.",
  teaserText: "Das persönliche Installationspaket für Selbstständige und Macher. Eigene Dateien weiterbearbeiten, Regeln einmal pflegen, Anbieter wechseln. Einmalig 199 €.",
  teaserLink: "Persönliches KI-System entdecken",
  storyEyebrow: "Eine Datei. Ein durchgehender Arbeitsstand.",
  storyTitle: "Aus „Wo war noch mal der Chat?“ wird „Öffne das Angebot“.",
  storyIntro: "Ein Beispiel aus dem Alltag: Du entwickelst mit KI einen Text für deine Homepage oder ein Kundenangebot.",
  storySteps: [
    { number: "01", title: "Erstellen", text: "Der Entwurf landet als ordentlich benannte Markdown-Datei in deinem eigenen System, nicht nur als Antwort im Chat." },
    { number: "02", title: "Wiederfinden", text: "Wochen später findet ein Agent mit Zugriff auf deinen Ordner den Text anhand von Thema und Dateinamen wieder." },
    { number: "03", title: "Weiterarbeiten", text: "Du gibst Feedback. Der Agent überarbeitet dieselbe Datei. Dein aktueller Arbeitsstand bleibt dort, wo du ihn brauchst." },
  ],
  fileTitle: "Schluss mit der Download-Upload-Schleife.",
  fileText: "Bei Word-, Excel- oder PDF-Dateien aus einem isolierten Chat kennst du das Hin und Her: herunterladen, speichern, nach einer Änderung erneut herunterladen, die lokal bearbeitete Version wieder hochladen. Ein Agent mit Zugriff auf deine freigegebenen Dateien arbeitet am aktuellen Stand. Welche Formate er direkt bearbeiten kann, hängt von seinen Werkzeugen ab.",
  rulesEyebrow: "Eine Änderung. Ein gemeinsamer Stand.",
  rulesTitle: "„Newsletter-Kunden siezen.“ Einmal festlegen.",
  rulesText: "Dein Schreibstil und deine Arbeitsregeln liegen in lesbaren Dateien. Änderst du die Anrede, können Claude Code und Codex beim nächsten Zugriff dieselbe aktuelle Regel verwenden. Du musst sie nicht in mehreren getrennten Chats und Anbieterprofilen nachpflegen.",
  rulesNote: "Die Agenten benötigen Zugriff auf den Systemordner. Gemini ist derzeit nur als Vorschau berücksichtigt.",
  ownTitle: "Dein Wissen bleibt als Datei bei dir.",
  ownText: "Kontext, Texte und Regeln liegen in deinem Ordner in lesbaren Formaten. Du kannst sie öffnen, sichern, ändern und mit einem anderen unterstützten Agenten weiterverwenden. So hängt dein Arbeitsstand nicht an einem einzelnen Chatverlauf oder Anbieter.",
  ownNote: "Die Quelldateien liegen lokal. Was du einem KI-Agenten zur Verarbeitung gibst, kann an dessen Modellanbieter übertragen und dort nach dessen Bedingungen verarbeitet werden.",
  packageEyebrow: "Was du für 199 € bekommst",
  packageTitle: "Ein vorbereiteter Arbeitsplatz für KI.",
  packageText: "Du erhältst das vollständige Installationspaket mit Struktur für persönlichen Kontext, Aufgaben und Wissen, gemeinsamen Arbeitsregeln, wiederverwendbaren Fähigkeiten und einer geführten Einrichtung. Du füllst das System mit deinen eigenen Angaben und Dateien.",
  packageItems: ["Vollständiges Installationspaket als Download", "Kontext- und Wissensstruktur in lesbaren Dateien", "Aufgabenstruktur, Kern-Skills und geführte Einrichtung", "Vorbereitung für Claude Code und Codex"],
  setupTitle: "So startest du",
  setupSteps: ["Paket herunterladen und auf deinem Rechner entpacken.", "Ordner mit Claude Code oder Codex öffnen und die geführte Einrichtung starten.", "Eigene Angaben, Arbeitsregeln und erste Dateien ergänzen."],
  requirementsTitle: "Das solltest du wissen",
  requirements: ["Für macOS und Windows mit WSL2. Native Windows-Terminals werden nicht unterstützt.", "Du brauchst einen geeigneten KI-Agenten sowie bash und Python 3. Anbieter-Abos oder Nutzungskosten sind nicht im Preis enthalten.", "Die Einrichtung machst du selbst. Persönliche Hilfe biete ich bei Bedarf separat gegen Bezahlung an.", "Bereitgestellte neue Paketversionen kannst du selbst herunterladen und einspielen. Eine feste Updatefrequenz ist nicht enthalten."],
  fitTitle: "Für wen passt das?",
  fitText: "Für Selbstständige und technisch orientierte Macher, die mit KI regelmäßig an echten Dateien und Projekten arbeiten wollen. Auch eine kleine Firma kann damit starten. Wenn ein Team, mehrere Systeme oder individuelle Abläufe eingerichtet werden sollen, ist die maßgeschneiderte Unternehmenslösung passender.",
  businessLink: "KI-System für Unternehmen ansehen",
  finalTitle: "Gib deiner KI einen Arbeitsplatz, der dir gehört.",
  finalText: "Das Paket kostet einmalig 199 €. Du richtest es für dich ein und arbeitest danach mit deinen Dateien und Regeln weiter.",
  contactNote: "Fragen oder Bedarf an individueller Einrichtung? Sprich mit mir.",
} as const;

type CopyShape = {
  [K in keyof typeof de]: (typeof de)[K] extends readonly (infer Item)[]
    ? readonly (Item extends { number: string; title: string; text: string }
      ? { number: string; title: string; text: string }
      : string)[]
    : string;
};

const en: CopyShape = {
  metaTitle: "Your personal AI system | Patrick Cipic Grübener",
  metaDescription: "Work with AI on your own files instead of scattered chats. A ready-to-set-up AI system for independent makers: €199 one time.",
  eyebrow: "Your personal AI system",
  heroTitle: "Your work should not be buried in a chat history.",
  heroText: "You draft a proposal with AI. Two months later, you want to revise it. Instead of hunting for the right chat, open the file in your system and continue working on it with your AI agent.",
  heroPoint: "One place for your files, context, and working rules.",
  priceLabel: "One-time package price",
  buy: "Buy now for €199",
  enquire: "Ask to buy",
  talk: "Book a conversation",
  checkoutPending: "Direct checkout is being prepared. You can enquire about buying now.",
  teaserTitle: "AI for your own work: one system instead of scattered chats.",
  teaserText: "The personal installation package for independent makers. Continue working on your files, maintain rules once, switch providers. €199 one time.",
  teaserLink: "Explore the personal AI system",
  storyEyebrow: "One file. One continuous working version.",
  storyTitle: "From “Where was that chat?” to “Open the proposal.”",
  storyIntro: "A familiar example: you draft website copy or a client proposal with AI.",
  storySteps: [
    { number: "01", title: "Create", text: "The draft becomes a clearly named Markdown file in your own system, rather than living only in a chat reply." },
    { number: "02", title: "Find", text: "Weeks later, an agent with access to your folder can find it by topic and file name." },
    { number: "03", title: "Continue", text: "You give feedback and the agent edits the same file. Your current work stays where you need it." },
  ],
  fileTitle: "Break the download-upload loop.",
  fileText: "With Word, Excel, or PDF files made in an isolated chat, the cycle is familiar: download, save, download again after a change, then reupload your locally edited version. An agent with access to your approved files works from the current version. Which formats it can edit directly depends on its tools.",
  rulesEyebrow: "One change. One shared source.",
  rulesTitle: "“Address newsletter customers formally.” Set it once.",
  rulesText: "Your writing style and working rules live in readable files. When you change a rule, Claude Code and Codex can use the same current version on their next access. You do not need to update separate chats and provider profiles.",
  rulesNote: "Agents need access to the system folder. Gemini support is currently a preview.",
  ownTitle: "Your knowledge stays in your files.",
  ownText: "Context, texts, and rules live in your folder in readable formats. You can open, back up, change, and reuse them with another supported agent. Your work is not tied to one chat history or provider.",
  ownNote: "Source files are stored locally. Content you give an AI agent to process may be sent to its model provider and handled under that provider’s terms.",
  packageEyebrow: "What you get for €199",
  packageTitle: "A prepared workspace for AI.",
  packageText: "You receive the complete installation package with a structure for personal context, tasks, and knowledge; shared working rules; reusable skills; and guided setup. You fill it with your own details and files.",
  packageItems: ["Complete installation package as a download", "Context and knowledge structure in readable files", "Task structure, core skills, and guided setup", "Prepared for Claude Code and Codex"],
  setupTitle: "Getting started",
  setupSteps: ["Download the package and unpack it on your computer.", "Open the folder in Claude Code or Codex and start guided setup.", "Add your details, working rules, and first files."],
  requirementsTitle: "Before you buy",
  requirements: ["For macOS and Windows with WSL2. Native Windows terminals are not supported.", "You need a suitable AI agent, bash, and Python 3. Provider subscriptions or usage fees are separate.", "You set it up yourself. Personal help is available separately for a fee.", "You can download and install new package versions when provided. No fixed update frequency is included."],
  fitTitle: "Who is it for?",
  fitText: "For self-employed people and technical makers who regularly work with AI on real files and projects. Small businesses can start with it too. If you need a team setup, multiple systems, or custom workflows, the tailored business solution is a better fit.",
  businessLink: "See the business AI system",
  finalTitle: "Give your AI a workspace that belongs to you.",
  finalText: "The package costs €199 once. Set it up for yourself, then keep working with your files and rules.",
  contactNote: "Questions or need a custom setup? Talk to me.",
};

const hr: CopyShape = {
  metaTitle: "Tvoj osobni AI sustav | Patrick Cipic Grübener",
  metaDescription: "Radi s AI-jem na vlastitim datotekama umjesto u razbacanim razgovorima. Pripremljen AI sustav za samostalne stvaratelje: jednokratno 199 €.",
  eyebrow: "Tvoj osobni AI sustav",
  heroTitle: "Tvoj rad ne bi trebao ostati zakopan u razgovoru.",
  heroText: "Napišeš ponudu uz pomoć AI-ja. Dva mjeseca poslije želiš je doraditi. Umjesto traženja starog razgovora, otvoriš datoteku u svojem sustavu i nastaviš raditi s AI agentom.",
  heroPoint: "Jedno mjesto za datoteke, kontekst i pravila rada.",
  priceLabel: "Jednokratna cijena paketa",
  buy: "Kupi za 199 €",
  enquire: "Pošalji upit za kupnju",
  talk: "Dogovori razgovor",
  checkoutPending: "Izravna kupnja još se priprema. Već sada možeš poslati upit.",
  teaserTitle: "AI za vlastiti rad: jedan sustav umjesto razbacanih razgovora.",
  teaserText: "Osobni instalacijski paket za samostalne stvaratelje. Radi na svojim datotekama, pravila mijenjaj jednom i biraj pružatelja usluga. Jednokratno 199 €.",
  teaserLink: "Otkrij osobni AI sustav",
  storyEyebrow: "Jedna datoteka. Jedna aktualna verzija.",
  storyTitle: "Od „Gdje je onaj razgovor?” do „Otvori ponudu.”",
  storyIntro: "Primjer iz prakse: uz AI pišeš tekst za web-stranicu ili ponudu klijentu.",
  storySteps: [
    { number: "01", title: "Izradi", text: "Nacrt spremiš kao jasno imenovanu Markdown datoteku u vlastitom sustavu, a ne samo kao odgovor u razgovoru." },
    { number: "02", title: "Pronađi", text: "Tjednima poslije agent s pristupom mapi može pronaći tekst prema temi i nazivu datoteke." },
    { number: "03", title: "Nastavi", text: "Daješ povratnu informaciju, a agent uređuje istu datoteku. Aktualan rad ostaje na pravom mjestu." },
  ],
  fileTitle: "Bez stalnog preuzimanja i ponovnog učitavanja.",
  fileText: "Kod Word, Excel ili PDF datoteka nastalih u izoliranom razgovoru slijedi poznati krug: preuzmi, spremi, nakon izmjene opet preuzmi, a lokalno uređenu verziju ponovno učitaj. Agent s pristupom odobrenim datotekama radi na aktualnoj verziji. Mogućnost izravnog uređivanja pojedinog formata ovisi o njegovim alatima.",
  rulesEyebrow: "Jedna promjena. Jedan izvor pravila.",
  rulesTitle: "„Kupcima se u newsletteru obraćamo s Vi.” Odredi jednom.",
  rulesText: "Stil pisanja i pravila rada nalaze se u čitljivim datotekama. Kad promijeniš pravilo, Claude Code i Codex pri sljedećem pristupu mogu koristiti isto aktualno pravilo. Ne moraš ga mijenjati u odvojenim razgovorima i profilima pružatelja usluga.",
  rulesNote: "Agenti trebaju pristup mapi sustava. Podrška za Gemini zasad je probna.",
  ownTitle: "Tvoje znanje ostaje u tvojim datotekama.",
  ownText: "Kontekst, tekstovi i pravila nalaze se u tvojoj mapi u čitljivim formatima. Možeš ih otvoriti, sigurnosno kopirati, mijenjati i koristiti s drugim podržanim agentom. Tvoj rad ne ovisi o jednom razgovoru ili pružatelju usluga.",
  ownNote: "Izvorne datoteke pohranjene su lokalno. Sadržaj koji predaš AI agentu na obradu može se poslati pružatelju modela i obraditi prema njegovim uvjetima.",
  packageEyebrow: "Što dobivaš za 199 €",
  packageTitle: "Pripremljen radni prostor za AI.",
  packageText: "Dobivaš cjelovit instalacijski paket sa strukturom za osobni kontekst, zadatke i znanje, zajedničkim pravilima rada, vještinama za višekratnu uporabu i vođenim postavljanjem. Nadopunjuješ ga svojim podacima i datotekama.",
  packageItems: ["Cjelovit instalacijski paket za preuzimanje", "Struktura konteksta i znanja u čitljivim datotekama", "Struktura zadataka, osnovne vještine i vođeno postavljanje", "Pripremljeno za Claude Code i Codex"],
  setupTitle: "Kako započeti",
  setupSteps: ["Preuzmi paket i raspakiraj ga na računalu.", "Otvori mapu u Claude Codeu ili Codexu i pokreni vođeno postavljanje.", "Dodaj svoje podatke, pravila rada i prve datoteke."],
  requirementsTitle: "Prije kupnje",
  requirements: ["Za macOS i Windows s WSL2. Izvorni Windows terminali nisu podržani.", "Potreban je odgovarajući AI agent te bash i Python 3. Pretplate ili troškovi korištenja pružatelja usluga plaćaju se zasebno.", "Sustav postavljaš samostalno. Osobna pomoć dostupna je zasebno uz naplatu.", "Nove verzije paketa, kada su dostupne, možeš sam preuzeti i instalirati. Nije uključena zajamčena učestalost ažuriranja."],
  fitTitle: "Kome odgovara?",
  fitText: "Samostalnim profesionalcima i tehnički orijentiranim stvarateljima koji redovito rade s AI-jem na stvarnim datotekama i projektima. Mogu ga koristiti i male tvrtke. Za timsku instalaciju, više sustava ili prilagođene tijekove rada prikladnije je poslovno rješenje.",
  businessLink: "Pogledaj AI sustav za tvrtke",
  finalTitle: "Daj svojem AI-ju radni prostor koji pripada tebi.",
  finalText: "Paket stoji jednokratno 199 €. Postavi ga za sebe i nastavi raditi na svojim datotekama prema svojim pravilima.",
  contactNote: "Imaš pitanja ili trebaš prilagođeno postavljanje? Javi mi se.",
};

export const kiSystemContent: Record<Language, CopyShape> = { de, en, hr };
